### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by fire** [gogogarrett/exbuf_plug#1]
What license is this?

**Comment by fire** [comment]
I want to remix this library so it uses https://github.com/wooga/eflatbuffers to handle input.

**Comment by gogogarrett** [comment]
Hello, 

Sorry I did not have one before. I have since added the MIT license. Feel free to do what you'd like with this code base :)

- https://github.com/gogogarrett/exbuf_plug/blob/master/LICENSE.md

**Comment by fire** [comment]
Thanks.
